add_newline = true

format = """
$hostname\
$localip\
$username\
$directory\
$character\
"""

right_format = """
$python\
$git_branch\
$git_commit\
$git_state\
$git_status\
$time\
"""

[fill]
symbol = ' '

[python]
symbol = " "
format = '[ $symbol$virtualenv ]($style)'

[time]
disabled = false
time_format = "%R"
format = '[ $time ]($style)'
utc_time_offset = "local"
style = "italic dimmed white"

[directory]
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[git_branch]
symbol = " "
format = '[$symbol$branch ]($style)'

[git_commit]
tag_symbol = '  '
format = '[$symbol$hash$tag ]($style)'

