theme = "onedark_transparent"

[editor]
color-modes = true
line-number = "relative"
end-of-line-diagnostics = "hint"
auto-format = true
rulers = [80]

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.file-picker]
git-ignore = true
hidden = false

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "diagnostics"]
center = ["version-control", "workspace-diagnostics"]
right = ["selections", "primary-selection-length", "register", "position", "file-encoding", "total-line-numbers", "position-percentage"]

# [editor.whitespace]
# render = "all"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.normal]
C-y = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
C-l = ":sh zellij run -n Lazgit -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/lazygit-picker.sh %{buffer_name}"
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
