theme = "onedark_transparent"

[editor]
bufferline = "multiple"
color-modes = true
line-number = "relative"
end-of-line-diagnostics = "hint"
auto-format = true

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
render = false
character = "┊" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.soft-wrap]
enable = true

# [editor.whitespace]
# render = "all"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[keys.normal]
C-y = ":sh zellij run -n Yazi -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open %{buffer_name}"
C-l = ":sh zellij run -n Lazgit -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/lazygit-picker.sh %{buffer_name}"
space.B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
